services:
  app:
    build:
      context: .
      args:
        - WEBSOCKET_URL=ws://localhost:8080
    environment:
      - SERVER_PORT=8080
    ports:
      - 8080:8080
    command: node server/app.js
