services:
  app:
    build:
      context: .
    image: ghcr.io/akashkarnatak/dronertc:0.1.0
    volumes:
      - ./receiver/env.js:/app/receiver/env.js
    environment:
      - SERVER_PORT=8080
    ports:
      - 8080:8080
    command: node server/app.js
