services:
  app:
    build:
      context: .
    image: ghcr.io/akashkarnatak/dronertc:0.1.1
    environment:
      - SERVER_PORT=$SERVER_PORT
      - WEBSOCKET_URL=$WEBSOCKET_URL
    ports:
      - $SERVER_PORT:$SERVER_PORT
    command: node server/app.js
